### ISSUE TITLE
mox3 archived & deprecated upstream, please update tests to not use it

### ISSUE THREAD

**Issue by robbat2** [google/nsscache#156]
mox3 is no longer available upstream and does not support python 3.9 or newer, so nsscache cannot be tested with newer python3

https://opendev.org/openstack/mox3/src/branch/master/README.rst

Please update the tests to use something else, so it can be tested.

**Comment by jaqx0r** [comment]
Yeah I would love someone to do this PR. It will probably be easiest if the
tests can be changed one at a time.

**Comment by antarus12345** [comment]
Hey Jaq, long time no see.

I have some patches for this (still WIP; but migrating to unittest.mock.) I'll try to submit em by this weekend.

-A

**Comment by jaqx0r** [comment]
G'day Alec!  That sounds wonderful.
