### ISSUE TITLE
Does not work offline.

### ISSUE THREAD

**Issue by wmantly** [google/nsscache#166]
Hello,

I am trying to use nsscache to allow login on desktops/laptops from a small openLDAP deployment while the device does not have a network connection.

I have set up nsscache, did an update and verify and everything seems in order. I have changed the nsswitch.conf file to have `ldap cache` and just `cachce`. Both work while the system is online, but once the network connection is removed, user login does not work.

How can nsscache be used offline? I do not understand why it doesn't work.

**Comment by jaqx0r** [comment]
Is libnsscache from https://github.com/google/libnss-cache installed?

**Comment by jaqx0r** [comment]
This is a pam issue, not a nsscache issue. The log line indicates to me
that pam requires an answer from LDAP, if I recall correctly you need to
mark that source with "sufficient" or remove it entirely and rely only on
db and cache.

**Comment by jaqx0r** [comment]
Oh, I just realised you're looking at the nss config but not pam. Check out
your /etc/pam.d and change how the LDAP module is configured.

**Comment by jaqx0r** [comment]
Now I think I understand what you're doing. nsscache isn't for PAM and so
isn't your solution here.

The user database is cached locally to speed up and improve availability of
nss lookups. It doesn't make authentication work offline.

You'll need an alternative design to also allow offline logins.

**Comment by wmantly** [comment]
oh, i see, Thank you for the help.
