### ISSUE TITLE
glibc makedb no longer compatible with berkeley db

### ISSUE THREAD

**Issue by jaqx0r** [google/nsscache#28]
Original [issue 27](https://code.google.com/p/nsscache/issues/detail?id=27) created by jaqx0r on 2012-06-27T00:14:13.000Z:

<b>What steps will reproduce the problem?</b>
1. Use nsscache on a system with glibc's new integrated db code (ex: Fedora 17)
2. Setup and run nsscache

<b>What is the expected output? What do you see instead?</b>
- after makedb is spawned off to create the db file, it later can't be opened by bsddb.btopen:

DEBUG:NssDbPasswdHandler:executing makedb: /usr/bin/makedb - /var/lib/misc/nsscache-cache-file-zuFOGl
DEBUG:NssDbPasswdHandler:17 entries written, 34 keys
DEBUG:NssDbPasswdHandler:verification started with /var/lib/misc/nsscache-cache-file-zuFOGl
udpate rmtree /var/lib/misc/nsscache-passwd-yAP1VQ
Traceback (most recent call last):
  File &quot;/bin/nsscache&quot;, line 33, in &lt;module&gt;
    return_value = nsscache_app.Run(sys.argv[1:], os.environ)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/app.py&quot;, line 242, in Run
    retval = command_callable().Run(conf=conf, args=args)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/command.py&quot;, line 235, in Run
    force_lock=options.force_lock)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/command.py&quot;, line 307, in UpdateMaps
    force_write=force_write)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/update/updater.py&quot;, line 256, in UpdateFromSource
    force_write, location=None)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/update/map_updater.py&quot;, line 79, in UpdateCacheFromSource
    return_val += self.FullUpdateFromMap(cache, source_map, force_write)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/update/map_updater.py&quot;, line 144, in FullUpdateFromMap
    return_val = cache.WriteMap(map_data=new_map)
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/caches/caches.py&quot;, line 212, in WriteMap
    if force_write or self.Verify(entries_written):
  File &quot;/usr/lib/python2.7/site-packages/nss_cache/caches/nssdb.py&quot;, line 214, in Verify
    db = bsddb.btopen(self.temp_cache_filename, 'r')
  File &quot;/usr/lib64/python2.7/bsddb/**init**.py&quot;, line 381, in btopen
    d.open(file, db.DB_BTREE, flags, mode)
bsddb.db.DBInvalidArgError: (22, 'Invalid argument -- __db_meta_setup: /var/lib/misc/nsscache-cache-file-zuFOGl: unexpected file type or format')

<b>What version of the product are you using? On what operating system?</b>

nsscache-0.21.17

```
# rpm -qf `which makedb`
glibc-common-2.15-37.fc17.x86_64

Fedora release 17 (Beefy Miracle)


<b>Please provide any additional information below.</b>

See https://bugzilla.redhat.com/show_bug.cgi?id=834912 for more info, and a &quot;working as intended&quot; response.
```

**Comment by hexedpackets** [comment]
I ran into this same issue in Arch with db version 5.3.28-2. I tried using the 'cache' backend as suggested, but unless I missed something it doesn't actually seem to be implemented. The only valid cache backends are 'files' and 'nssdb'.

**Comment by jaqx0r** [comment]
What errors do you get when configuring the cache backends? It is the only
one that is battle tested, so I am very surprised to hear it doesn't work.

No one new should use the nssdb backend, and I'd delete it except I don't
know if any existing users rely on it.

**Comment by hexedpackets** [comment]
I tried setting `cache = cache` in my nsscache.conf and the following is thrown when running nsscache update:

```
Traceback (most recent call last):
  File "/usr/sbin/nsscache", line 33, in <module>
    return_value = nsscache_app.Run(sys.argv[1:], os.environ)
  File "/usr/lib/python2.7/site-packages/nss_cache/app.py", line 240, in Run
    retval = command_callable().Run(conf=conf, args=args)
  File "/usr/lib/python2.7/site-packages/nss_cache/command.py", line 230, in Run
    force_lock=options.force_lock)
  File "/usr/lib/python2.7/site-packages/nss_cache/command.py", line 303, in UpdateMaps
    force_write=force_write)
  File "/usr/lib/python2.7/site-packages/nss_cache/update/updater.py", line 272, in UpdateFromSource
    cache = cache_factory.Create(self.cache_options, self.map_name)
  File "/usr/lib/python2.7/site-packages/nss_cache/caches/cache_factory.py", line 76, in Create
    raise RuntimeError('cache not implemented: %r' % (cache_name,))
RuntimeError: cache not implemented: 'cache'
```

Looking at cache_factory.py, only files and nsscache get registered as cache implementations: https://github.com/google/nsscache/blob/master/nss_cache/caches/cache_factory.py#L84-L85

**Comment by hexedpackets** [comment]
Have you had a chance to look at this any further? I'm happy to switch backends, but can't see how to do that currently.

**Comment by robbat2** [comment]
@hexedpackets 
use 'cache = files'

**Comment by jaqx0r** [comment]
Thanks Robin. That config option eluded me, and now looking at it, it is
not very clear what it does!

**Comment by jaqx0r** [comment]
I've sent a documentation fix; it's still confusing but at least it's now
correct.
