### ISSUE TITLE
/etc/group.cache lists group members with distinguished name instead of username

### ISSUE THREAD

**Issue by jaqx0r** [google/nsscache#35]
Original [issue 34](https://code.google.com/p/nsscache/issues/detail?id=34) created by jaqx0r on 2014-09-07T08:33:27.000Z:

<b>What steps will reproduce the problem?</b>
1.Group definition in LDAP
dn: cn=thglanzm,ou=Groups,dc=domain,dc=de
objectClass: posixGroup
cn: thglanzm
gidNumber: 10074
memberUid: uid=thglanzm,ou=People,dc=domain,dc=de
structuralObjectClass: posixGroup
entryUUID: f3fffb3c-8994-1033-82c3-d574d9524b6e
creatorsName: cn=manager,dc=domain,dc=de
createTimestamp: 20140616112732Z
entryCSN: 20140616112732.904794Z#&nbsp;000000#&nbsp;000#&nbsp;000000
modifiersName: cn=manager,dc=domain,dc=de
modifyTimestamp: 20140616112732Z
1. Nsscache Configuration:
   [DEFAULT]
   source = ldap
   cache = files
   maps = passwd, group, shadow, sshkey
   timestamp_dir = /var/lib/nsscache
   ldap_uri = ldap://ldap1
   ldap_base = dc=domain,dc=de
   ldap_filter = (objectclass=posixAccount)
   ldap_bind_dn = &quot;cn=pam,dc=domain,dc=de&quot;
   ldap_bind_password = &quot;password&quot;
   nssdb_dir = /var/lib/misc
   files_dir = /etc
   files_cache_filename_suffix = cache

[passwd]
ldap_base = ou=People,dc=domain,dc=de

[group]
ldap_base = ou=Groups,dc=domain,dc=de
ldap_filter = (objectclass=posixGroup)
rfc2307bis = 1

[shadow]
ldap_filter = (objectclass=shadowAccount)

[sshkey]
ldap_base = ou=People,dc=domain,dc=de
1. Run nsscache update and cat /etc/group
   grep ^thglanzm /etc/group.cache
   thglanzm:*:10074:uid=thglanzm,ou=People,dc=domain,dc=de

<b>What is the expected output? What do you see instead?</b>

Expected Output:
grep ^thglanzm /etc/group.cache
thglanzm:*:10074:thglanzm

I see instead:
grep ^thglanzm /etc/group.cache
thglanzm:*:10074:uid=thglanzm,ou=People,dc=domain,dc=de

<b>What version of the product are you using? On what operating system?</b>

I used the latest release nsscache-0.23.tar.gz and the git head as of
2014-09-07.

<b>Please provide any additional information below.</b>

I wrote a small patch which I assume is wrong because it fights the symptoms instead of removes the root cause. Can someone who knows python and knows the code base better, please write a proper patch?

**Comment by oregszun** [comment]
Hello,

I have just checked out the master branch and built nsscache, and the issue mentioned here still persists!
The /etc/group.cache lists group members with distinguished name instead of username.
This is the same scenario as the earlier reporter used.

Has not been fixed already?

**Comment by jaqx0r** [comment]
Please share your configuration and the command line you used, an example
ldif of one record from LDAP.  Also you could enable debug log output and
see if you can see a suitable error message.

**Comment by oregszun** [comment]
nsscache.conf

[DEFAULT]
source = ldap
cache = files
maps = passwd, group, shadow, sshkey
timestamp_dir = /var/lib/nsscache
ldap_uri = ldap://w.x.y.z
ldap_base = dc=whatever,dc=com
ldap_filter = (objectclass=posixAccount)
ldap_bind_dn = "cn=Manager,dc=whatever,dc=com"
ldap_bind_password = ******

nssdb_dir = /var/lib/misc
files_dir = /etc
files_cache_filename_suffix = cache

[passwd]
ldap_base = ou=People,dc=whatever,dc=com

[group]
ldap_base = ou=Groups,dc=whatever,dc=com
ldap_filter = (objectclass=posixGroup)

[shadow]
ldap_base = ou=People,dc=whatever,dc=com
ldap_filter = (objectclass=shadowAccount)

[sshkey]
ldap_base = ou=People,dc=whatever,dc=com
ldap_filter = (objectclass=ldapPublicKey)

**Comment by oregszun** [comment]
dn: cn=whatever-ldap,ou=Groups,dc=whatever,dc=com
objectClass: posixGroup
cn: whatever-ldap
gidNumber: 5002
memberUid: uid=user1,ou=People,dc=whatever,dc=com
memberUid: uid=user2,ou=People,dc=whatever,dc=com
memberUid: uid=user3,ou=People,dc=whatever,dc=com
memberUid: uid=user4,ou=People,dc=whatever,dc=com
...

**Comment by oregszun** [comment]
**ldap_rfc2307bis_alt = 1**

[root@build ~]# head -n 1 /etc/group.cache
whatever-ldap:*:5002:
[root@build ~]#

**ldap_rfc2307bis_alt = 0**

[root@concar-build ~]# head -n 1 /etc/group.cache
whatever-ldap:*:5002:uid=user1,ou=People,dc=caritc,dc=de,uid=user2,ou=People,dc=caritc,dc=de,uid=user3...

**Comment by oregszun** [comment]
[root@build nsscache]# nsscache -v update
INFO:NSSCacheApp:using nss_cache library, version 0.32
INFO:config:Configured maps are: passwd, group, shadow, sshkey
INFO:Update:Updating and verifying passwd cache.
INFO:Update:Updating and verifying passwd cache.
INFO:MapUpdater:Missing previous timestamp, defaulting to a full sync.
INFO:Update:Updating and verifying group cache.
INFO:Update:Updating and verifying group cache.
INFO:MapUpdater:Missing previous timestamp, defaulting to a full sync.
INFO:Update:Updating and verifying shadow cache.
INFO:Update:Updating and verifying shadow cache.
INFO:MapUpdater:Missing previous timestamp, defaulting to a full sync.
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:root:Ignored password that was not in crypt format
INFO:Update:Updating and verifying sshkey cache.
INFO:Update:Updating and verifying sshkey cache.
INFO:MapUpdater:Missing previous timestamp, defaulting to a full sync.
INFO:NSSCacheApp:Exiting nsscache with value 0 runtime 0.080000
