### ISSUE TITLE
Symbol visibility?

### ISSUE THREAD

**Issue by kev009** [google/nsscache#43]
We saw some "weirdness" (random crashes in an unrelated app's pthread locks) after loading this on one box.

I'm wondering if the symbol visibility is somehow causing trouble.  I notice other libnss implementations use libtool and export only the bare minimum symbols.

If I port the current makefile to autotools and libtool, would you accept the PR?

**Comment by jaqx0r** [comment]
I would; we originally did not because of our limited platform target but
if you want to go down the path of satanic ritual that is autogoats, I will
accept the PR ;-)

**Comment by kev009** [comment]
Opened this on the wrong project.  Will port and PR
