### ISSUE TITLE
Dies if using http and gets an empty response from server

### ISSUE THREAD

**Issue by elicriffield** [google/nsscache#44]
http_ts_string does not get set if the response from the server is empty, Here is a patch that is a quick fix that shows where the problem is.

From d64a55eb5ecd06c8aeb90a45f695db55e6080b81 Mon Sep 17 00:00:00 2001
From: Eli Criffield <elicriffield@gmail.com>
Date: Wed, 20 May 2015 13:04:55 -0500
Subject: [PATCH 1/1] add http_ts_string before its referenced

---
 nss_cache/sources/httpsource.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/nss_cache/sources/httpsource.py b/nss_cache/sources/httpsource.py
index cc4f3d5..db91214 100644
--- a/nss_cache/sources/httpsource.py
+++ b/nss_cache/sources/httpsource.py
@@ -269,6 +269,7 @@ class UpdateGetter(object):
     headers = headers.split('\r\n')
     last_modified = conn.getinfo(pycurl.INFO_FILETIME)
     self.log.debug('last modified: %s', last_modified)
+    http_ts_string = 'Sun, 01 Nov 1970 00:00:00 GMT'
     if last_modified == -1:
       for header in headers:
         if header.lower().startswith('last-modified'):
-- 
2.2.0.rc0.207.ga3a616c

**Comment by jaqx0r** [comment]
Doh, thanks!

**Comment by jaqx0r** [comment]
This was fixed by https://github.com/google/nsscache/pull/49
