### ISSUE TITLE
Support uniqueMember to identify members of groups from rfc2307bis specification

### ISSUE THREAD

**Issue by tomgreen66** [google/nsscache#46]
We use uniqueMember attribute to identify group membership and was an alternate (maybe earlier) method in the draft rfc2307bis specification (the member attribute is already supported).  It seems  the rfc2307bis is now an expired specification.

I had originally made the changes before I saw the new support for the other rfc2307bis member attribute and had approached it slightly differently.  I wanted to query the DN for each uniqueMember in a group to get the uid, rather than assume the cn and uid are the same.  This is performed in a new function called PostProcess.  For example my first attempt at merging my old code to the new version in commit 8b4cc2242c7a76ae8a39c46412cd5667d7e60bca and is untested currently (but the previous version worked fine so the idea works).

We may be able to just use the current member method (and just change it to also support uniqueMember) but comments welcome whether my approach has any merit where uid and cn do not have to be identical.

**Comment by jaqx0r** [comment]
I dont remember how 2307bis works, but even though it's expired, people use it so it's  worth supporting. Sounds like a reasonable idea, if the current default is preserved, and you add tests. How about posting a PR and we can look at the code?
