### ISSUE TITLE
Please tag a new release!

### ISSUE THREAD

**Issue by robbat2** [google/nsscache#65]
Please tag a new release, for inclusion in other distributions (not just debian).

**Comment by jaqx0r** [comment]
version/0.30 is the last release and is tagged here https://github.com/google/nsscache/releases/tag/version%2F0.30

Are you talking about something else?

**Comment by robbat2** [comment]
Version 0.31 is what I meant ;-).

**Comment by jaqx0r** [comment]
Oh I see!  It's done just now :)
