### ISSUE TITLE
Example AuthorizedKeysCommand returns keys for other users if the username is a substring

### ISSUE THREAD

**Issue by robbat2** [google/nsscache#67]
The example AuthorizedKeysCommand has a security bug: It uses an awk regex compare to find the sshkey from the username.

Consider the dataset of:
```
rob:key
robbat2:key
grobian:key
```
An input of `rob` to the example command will return the keys for all 3 users. The AWK match should be an exact match instead of substring/regex.

**Comment by robbat2** [comment]
I have implemented a much better command that you can take here:
https://dev.gentoo.org/~robbat2/nsscache-0.30-gentoo-authorized-keys-command.py

**Comment by jaqx0r** [comment]
Wow, awkward.

Please submit this as a pull request to the examples directory :)
