### ISSUE TITLE
Tagging of versions

### ISSUE THREAD

**Issue by kev009** [google/nsscache#69]
Hi,

You've been updating the debian/ tags but not the version/ tags.  Can you update the version tag so other OSes can point to it for packaging?

**Comment by jaqx0r** [comment]
I'm not sure what's missing: https://github.com/google/nsscache/releases/tag/version%2F0.30 exists, as does the tag for version/0.28 and version/0.29.

There hasn't been a release since 0.30.

**Comment by kev009** [comment]
My mistake, I thought there were some changes in the debian branch, but I was looking at master.

**Comment by jaqx0r** [comment]
I've marked a new version 0.31 to pick up the addition of a consul source.
