### ISSUE TITLE
nsscache doesn't update group cache from ldap source

### ISSUE THREAD

**Issue by cwarner-mdsol** [google/nsscache#83]
If one has ldap as a source and updates on the server. nsscache neglects any updates to the group mappings. This is a relatively new finding, and the only work around seems to be completely removing the cache and indexes and pulling down fresh mappings.

Example:

ldap_base= ou=Groups,dc=example,dc=net

[remove group from user]
nsscache update
nsscache status

NSS map: group
last-modify-timestamp: Sat Aug 18 00:07:17 2018

Where the modify timestamp is incorrect as in, the file for group mappings hasn't been updated.

This is based on nsscache 0.36. At this point i'm not able to delve further to pin point exacts but if anyone comes across this the work around is above. Maybe if I can a couple of spare cycles i'll dig deeper.

**Comment by jaqx0r** [comment]
Can you turn on verbose logging and post the complete log when you run an
update please?

**Comment by cwarner-mdsol** [comment]
This looks like it's working now, there's a duplicate key in the groups mapping. Let me try to create a reproducer with details. If not it might be possible a node in the cluster was serving stale information, or something along those lines.

**Comment by cwarner-mdsol** [comment]
Closing, i'm unable to reproduce; if I see the behavior again i'll reopen with more debug data. I'll chalk this one up to nsscache requesting from a cluster node that had stale data so the change wasn't made.

**Comment by jaqx0r** [comment]
Curious. I wonder if we can add more logging to help debug this?

**Comment by cwarner-mdsol** [comment]
@jaqx0r It would certainly make it easier to tell in this specific case. As you can imagine trawling the ldap logs to see what exactly happened over a cluster is near impossible and laborious. At that point, I just literally didn't have the bandwidth to properly debug as I was on  slow mobile link in the middle of no where. What are you thinking?

**Comment by jaqx0r** [comment]
I actually don't have a thought on what to do about it, was hoping you
could recommend the sort of information you were after and we can try to
converge on a solution.
