### ISSUE TITLE
is nsscache python3 compatible?

### ISSUE THREAD

**Issue by sandrotosi** [google/nsscache#89]
travis config points to some python3 images, but if you run tests there, they fail as the code is clearly not ready yet (print statements all over, and other python2-isms).

is there any effort to port it to python3 anytime soon?

In Debian we're trying to phase out python2 during this development cycle.

thanks!

**Comment by jaqx0r** [comment]
There's no active effort at the moment but I love pull requests.

**Comment by 3c2b2ff5** [comment]
I modifed the the print functions, exceptions, imports, assets in test files and modified the `nss.py`and `nss_tets.py` and the `maps.py` to pass Python 3 test.
Now I am struggling with string/byte handling for ldapsource.

**Comment by jaqx0r** [comment]
I think we need to migrate to use the ldap3 library instead of python-ldap,
as the latter only works with python2 but "ldap3" claims to work with both
versions.

https://ldap3.readthedocs.io/

**Comment by 3c2b2ff5** [comment]
I thought about a while a go. Well that means a lot  of work. I found [python3-ldap](https://packages.debian.org/buster/python3-ldap), isn't it the python3 version of [python-ldap](https://packages.debian.org/buster/python-ldap)?

**Comment by 3c2b2ff5** [comment]
when I run my [pull request](https://github.com/google/nsscache/pull/95/commits/a4f8f3967d42dd47de2604d590d79d6e3ca60e45) with Python 3 I get the following error, this has to do with python-ldap library I guess and how it returns the data, so either go through the code and make it Python 3 compatible, which can be very time consuming and frustrating or import to python3-ldap which is Python3 only as I understand or migrate to ldap3, which claims to do both.
```
root@test: # python3 /usr/sbin/nsscache update -f
Traceback (most recent call last):
  File "/usr/sbin/nsscache", line 34, in <module>
    return_value = nsscache_app.Run(sys.argv[1:], os.environ)
  File "/usr/lib/python3/dist-packages/nss_cache/app.py", line 240, in Run
    retval = command_callable().Run(conf=conf, args=args)
  File "/usr/lib/python3/dist-packages/nss_cache/command.py", line 230, in Run
    force_lock=options.force_lock)
  File "/usr/lib/python3/dist-packages/nss_cache/command.py", line 303, in UpdateMaps
    force_write=force_write)
  File "/usr/lib/python3/dist-packages/nss_cache/update/updater.py", line 275, in UpdateFromSource
    force_write, location=None)
  File "/usr/lib/python3/dist-packages/nss_cache/update/map_updater.py", line 75, in UpdateCacheFromSource
    location=location)
  File "/usr/lib/python3/dist-packages/nss_cache/sources/source.py", line 63, in GetMap
    return self.GetPasswdMap(since)
  File "/usr/lib/python3/dist-packages/nss_cache/sources/ldapsource.py", line 420, in GetPasswdMap
    since=since)
  File "/usr/lib/python3/dist-packages/nss_cache/sources/ldapsource.py", line 664, in GetUpdates
    obj_ts = self.FromLdapToTimestamp(obj['whenChanged'][0])
  File "/usr/lib/python3/dist-packages/nss_cache/sources/ldapsource.py", line 572, in FromLdapToTimestamp
    t = time.strptime(ldap_ts_string, '%Y%m%d%H%M%S.0Z')
  File "/usr/lib/python3.7/_strptime.py", line 571, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.7/_strptime.py", line 326, in _strptime
    raise TypeError(msg.format(index, type(arg)))
TypeError: strptime() argument 0 must be str, not <class 'bytes'>
```

**Comment by jaqx0r** [comment]
I'm happy to go to Python3 only if that simplifies matters.

**Comment by 3c2b2ff5** [comment]
I would also suggest to go with python3 only, since Python2 EOL is in few months, so it doesn't make any sense to go through he code or use cross-version framework like six.

**Comment by 3c2b2ff5** [comment]
Python3 represent the object data as bytes. An object looks like this:
```
{'displayName': [b'Test User'], 'objectSid': [b'\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\xa0e\xcf~xK\x9b_\xe7|\x87p\t\x1c\x01\x00'], 'sAMAccountName': [b'user'], 'pwdLastSet': [b'132144982087435710'], 'whenChanged': [b'20191020171614.0Z']}
```
`nsscache`does string as well bytes operations with the object data, for instance writing to cache needs a byte-like object, however string methods need a string object.

In Python 2 this wasn't problem, since bytes are treated as strings an vise versa. Now we need to specify it all over the code, so if we keep the the byte objects, we have to decode them to string where ever needed in the code, or the other way around, which I think is the better way, especially for writing the cache, a passwd entry must be a string, other wise will end up with an empty cache.

**Comment by 3c2b2ff5** [comment]
I made few changes to merge to Python 3 only, caching and verifying works, at least for AD. Still have 34 errors when I do the runtests. But I am on it.

**Comment by jaqx0r** [comment]
I've merged in your python3_second branch locally here and started working
on the rest of the issues.

There's a lot in the nssdb cache module about string to bytes conversions,
and a few behaviour changes in mox3, and a few actual bugs that python3 is
correctly erroring on.

Still a WIP though, but I'll merge it upstream.

**Comment by 3c2b2ff5** [comment]
So you want to git rid of Python 2 completely and not supporting both. Its good. I am curious about the errors you  will fix.

**Comment by 3c2b2ff5** [comment]
If you want me to work on anything, just let me know.

**Comment by 3c2b2ff5** [comment]
I could fix some nssdb errors and failures in [python3_second](https://github.com/3c2b2ff5/nsscache/tree/python3_second), further more I changed some imports to import only the library needed, I removed duplicates in requirements.txt.

Now there are `FAILED (failures=2, errors=3, skipped=7)`

I hope I can get through the rest, unless you already have a fix.

**Comment by jaqx0r** [comment]
Yep I did mean that we should not keep python 2 around. Sorry if that
didn't come across correctly.

I've fixed all but two failures now which look like encoding errors in
consulsource.py.

**Comment by 3c2b2ff5** [comment]
I fixed one failure in `conulsource.py` it seems the default password if empty the returned default value `*` will be encoded:
```
    map_entry.passwd = entry.get('passwd', '*')
    if isinstance(map_entry.passwd, bytes):
      map_entry.passwd = map_entry.passwd.decode('ascii')
```

**Comment by 3c2b2ff5** [comment]
I just pushed my last changes to [python3_second](https://github.com/3c2b2ff5/nsscache/tree/python3_second)

**Comment by 3c2b2ff5** [comment]
btw if you changed the lambda expression this way:
```
if any(c in name for c in map(lambda x: x, [' ', ':', '\n'])):
```
you can pass strings in all the tests except the load bdb cache file. It seems `btopen` expect a byte-like object. In my changes I modified the lambda expression and removed the byte like from `consulsource_test.py`.

I just pushed a cosmetic change in `ldapsource_test.py`

**Comment by 3c2b2ff5** [comment]
shall I make a pull request with my resent changes ynd you modify it accordingly to your fixes for the errors?

**Comment by jaqx0r** [comment]
Yes please!

**Comment by 3c2b2ff5** [comment]
I realized that ` self.assertEqual(self.good_entry, group_map.PopItem())` in `consulsource_test.py` breaks the tests for empty members, it doesn't get further to `self.assertEqual(self.good_entry, entry)` in empty groups, if it is commented out the test succeeds.
The open still need to be closed, I closed the others but I've been struggling with these two:
```
  func(self, *args, **kwargs)
Object allocated at (most recent call last):
  File "/usr/lib/python3.7/os.py", lineno 1026
    return io.open(fd, *args, **kwargs)
..../opt/nsscache/nss_cache/caches/caches.py:101: ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  self.temp_cache_file = os.fdopen(fd, 'w+b')
Object allocated at (most recent call last):
  File "/usr/lib/python3.7/os.py", lineno 1026
    return io.open(fd, *args, **kwargs)
/usr/lib/python3/dist-packages/mox3/mox.py:2139: ResourceWarning: unclosed file <_io.BufferedRandom name=4>
  func(self, *args, **kwargs)
Object allocated at (most recent call last):
  File "/usr/lib/python3.7/os.py", lineno 1026
    return io.open(fd, *args, **kwargs)
...............................................................................................s....ss....s.s....ss.........................../usr/lib/python3/dist-packages/mox3/mox.py:2139: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpht28x68x/pidfile' mode='a+' encoding='UTF-8'>
  func(self, *args, **kwargs)
Object allocated at (most recent call last):
  File "/opt/nsscache/nss_cache/lock.py", lineno 108
    self._file = open(filename, 'a+')
.../usr/lib/python3/dist-packages/mox3/mox.py:2139: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpw8266zwv/pidfile' mode='a+' encoding='UTF-8'>
  func(self, *args, **kwargs)
Object allocated at (most recent call last):
  File "/opt/nsscache/nss_cache/lock.py", lineno 108
    self._file = open(filename, 'a+')
```

**Comment by jaqx0r** [comment]
As of HEAD now ./runtests.py passes on all tests in python3.

There's more work to do but I think we can close this bug and tag a release.

Thanks @3c2b2ff5 for your help!

**Comment by 3c2b2ff5** [comment]
Grandiose! Please let me know if how you want to proceed and what is the next step to take. I'll be happy to help.

**Comment by jaqx0r** [comment]
I've filed a couple of new issues that I've thought of, but for now can you
just do some testing of the latest code to make sure it's working as
expected? I am assuming that we have missed something :)

**Comment by 3c2b2ff5** [comment]
Normally yes. I'll do next week excessive tests on ldapsource, with AD and openldap. Unfortunately I cannot test the other modules, we have multiple consul cluster running in the company but as long I don't understand the code, any approach in this direction will fail.

**Comment by jaqx0r** [comment]
That's fine, thanks! As much as you are able to do is appreciated!
